linters:
  enable:
    - errname
    - gocheckcompilerdirectives
    - gocritic
    - gocyclo
    - godot
    - lll
    - makezero

linters-settings:
  gocyclo:
    min-complexity: 15
  lll:
    tab-width: 8
    line-length: 99
