#!/usr/bin/env bash

## Any comments that start with two hashes are bashdoc comments.
## Comment blocks separated by blank lines from any code are
## general narrative comments at the file level.

# This is a top-level comment, that bashdoc doesn't pick up.

## Set `TEST_SCRIPT_HOME` to set where `test-script` should look for its data files.
## If not set, defaults to `$HOME`.
: "${TEST_SCRIPT_HOME:=${HOME}}"

## `myfunction` greets the user
function myfunction() {
    # This is a comment inside of a function
    echo "Hello, World"
}

# There are no bashdoc comments, so this function will show up in the docs without any extra text.
function anotherone() {
    echo "Goodbye"
}

# PRIVATE tells bashdoc to not add this function to the documentation
## PRIVATE: hidden_func
function hidden_func() {
    echo "This is private"
}
